// components/Projects.vue
<template>
  <div
    class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4"
  >
    <Project
      v-for="project in projects"
      :key="project.id"
      :name="project.name"
      :date="project.pushed_at"
      :link="project.html_url"
    />
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import Project from './Project.vue'

const projects = ref([])

onMounted(async () => {
  const response = await fetch(
    `https://api.github.com/users/evrwaq/repos?per_page=100`
  )
  const data = await response.json()
  console.log(data)
  projects.value = data
})
</script>

// src/components/MainCard/components/Projects/Projects.tsx
import { useEffect, useState } from 'react'
import Project from './components/Project'
import './Projects.css'

type Repos = {
  id: number
  name: string
  description: string
  html_url: string
}

function Projects() {
  const [repos, setRepos] = useState<Repos[]>([])

  useEffect(() => {
    fetch('https://api.github.com/users/evrwaqe/repos')
      .then((response) => response.json())
      .then((data) => {
        setRepos(data)
      })
      .catch((error) => console.error('Error searching for projects:', error))
  }, [])

  return (
    <div className="projects-container">
      <h1>Projects</h1>

      <div className="inner-projects-container">
        {repos.map((repo) => (
          <Project
            key={repo.id}
            name={repo.name}
            description={repo.description}
            url={repo.html_url}
          />
        ))}
      </div>
    </div>
  )
}

export default Projects
